module.exports = {
    // ... require("./addmagic.js"),
    ... require("./automagic.js"),
    ... require("./cat.js"),
    ... require("./cd.js"),
    ... require("./cp.js"),
    ... require("./dhist.js"),
    ... require("./dirs.js"),
    ... require("./echo.js"),
    ... require("./env.js"),
    ... require("./exec.js"),
    ... require("./history.js"),
    ... require("./inspect.js"),
    ... require("./loadpy.js"),
    ... require("./ls.js"),
    ... require("./lsmagic.js"),
    ... require("./mkdir.js"),
    ... require("./mv.js"),
    ... require("./npm.js"),
    ... require("./pip.js"),
    ... require("./popd.js"),
    ... require("./pushd.js"),
    ... require("./pwd.js"),
    ... require("./quickref.js"),
    ... require("./report.js"),
    ... require("./require.js"),
    ... require("./rm.js"),
    ... require("./rmdir.js"),
    ... require("./script.js"),
    ... require("./sx.js"),
    ... require("./stubs.js"),
    ... require("./who.js"),
    ... require("./whos.js"),
};
